export default function RootHead() {
  return (
    <>
      <title>Threadoss: Generate Twitter Threads like a Boss</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </>
  );
}
