import { Html, Head, Main, NextScript } from 'next/document';

export default function Document() {
  return (
    <Html lang="en" className={`h-full bg-gray-100`}>
      <Head />
      <title>Threadoss: Generate Twitter Threads like a Boss</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <body className="h-full">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
